# Generated by Django 4.2.3 on 2023-08-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('accounts', models.ManyToManyField(related_name='user', to='api.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='transactions',
            field=models.ManyToManyField(related_name='account', to='api.transaction'),
        ),
    ]
