# Generated by Django 4.2.3 on 2023-08-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='transactions',
            field=models.ManyToManyField(to='api.transaction'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='accounts',
            field=models.ManyToManyField(to='api.account'),
        ),
    ]
