# Generated by Django 4.2.3 on 2023-09-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_debtrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='debt_records',
            field=models.ManyToManyField(blank=True, related_name='user', to='api.debtrecord'),
        ),
    ]
