# Generated by Django 4.1.7 on 2023-04-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_auctionlistings_auctionlisting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='current_bid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='image_URL',
            field=models.TextField(blank=True, null=True),
        ),
    ]
