# Generated by Django 4.1.7 on 2023-04-12 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctionlisting_current_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='lister',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
