# Generated by Django 4.1.7 on 2023-04-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctionlisting_lister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='lister',
        ),
    ]
