# Generated by Django 4.1.7 on 2023-04-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auctionlisting_lister'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='starting_bid',
            new_name='bid',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='current_bid',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('NONE', 'No Category Listed'), ('FSHN', 'Fashion'), ('TOYS', 'Toys'), ('ELEC', 'Electronics'), ('HOME', 'Home'), ('MISC', 'Miscellaneous')], default='NONE', max_length=64),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
