# Generated by Django 4.1.7 on 2023-04-16 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auctionlisting_watchlisted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='watchlisted_by',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
