name: CS50W CI

on: 
  push:
    branches: [master]

jobs:
  react-app-workflow:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 18.17.0
              uses: actions/setup-node@v2
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm i

            - name: format
              run: npm run prettier
